### ISSUE TITLE
Index condition does only identify impacted pk on upsert and not on patch or update

### ISSUE THREAD

**Issue by nonken** [tywalch/electrodb#366] opened 2024-03-19 08:37 UTC
**Describe the bug**
I have the following index:

```
entriesByEffectiveDate: {
  index: 'gsi3pk-gsi3sk',
  condition: (attr) => attr.effectiveAt !== 'n/a',
  pk: {
    field: 'gsi3pk',
    composite: ['organizationId']
  },
  sk: {
    field: 'gsi3sk',
    composite: ['portfolioId', 'effectiveAt']
  }
}
```

When updating an item using `.update` the resulting DynamoDB query only has `gsi3sk` set and not `gsi3pk`. When making the same call using `.upsert` it works, but I need to provide all available fields which requires me to fetch the item first. 

```
const { data, error } = await Entity.upsert({
  id,
  organizationId
}).set(obj)
```

I dug in a bit deeper and it looks like that [_getIndexImpact](https://github.com/tywalch/electrodb/blob/master/src/entity.js#L3107) will not return the `pk` in my case because organizationId is not provided in the attributes. The `sk` does get set resulting in a record without a `pk`.

It can be that I am not understanding the intend correctly, but my expectation was that this would work for update or patch calls.

**ElectroDB Version**
2.13.1

**ElectroDB Playground Link**
[Playground](https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAY1IBfbhiiSwAIkRwjVSzABGNgNzijUPrgVUGFwRSAF5bTShUDAB9AKC4aL4GSTgPLx8-MH4nTTAwvjgWVXUtAApRMCUKsElYRAAuKsrK4gxDE0aAcio8Kk78asrsrS6ev37BsH1MXCwfLoBGTurTAcqGKicsF1QxxsVJrBh9ycqqTWk4Lr9sPgBzCebm8jQscmOwJ3Q1p7I4BhgAHk+AhNI0vnBJqtJnI7gw+FgAF4bOZ8ACSHwOv0+FyuYE6Nyw90evxeqDecA+EJ+T3IAOBoPBGHQUJpYAYRm8qHUGJO2POl2uW2JrMmRjpPRgAEEqHzfgK8QThQ82ZU6UCQWDPsy4Kq-q93kzvqcwPAuAxKLKwKUAJR5AB8YAKRQAIhs4LaAHRUKAAKR0gIAcra9cQrbaHU7CmA3T0vT7-UHbaKnqhpDB3dKrVj5bihbcVSaWBsjHQuiASbS4AbKUbdSazRbqI0IyFHc6Y+7436A8GbaG4OG7W2o66uzbvT2kzaU80w1Rglm5U8FfmiYXsY3LV0+MAGMsntCnnAuFwHBppjLl81V-jCcS9Vvm-jd-vZ2c801c4K78rK89q3JQ1tRZQ82SMd07jkLUcxXT8lQLf81UAikqR1d92VqblsxNW8EPXJD9SA2sQMhMDJngXBxSwaQNHmL84J-fCRUPFYfiJeAAA88GvbJeFwa9KmkABrQTmi4HAEA+ToRMIypvBkKBZh6RoAG1OlheEkRRHwMU6ABdE0j1+XBRIY34JMQaTTLksAFNkZS8XUo4DKMjC+JwXAACFNClTlInUMSOLgTiujuWYFhEgBacKsAWUyouCzjCJEsTKksqSwoi2S9XkqwHPYJyNIwOEEWROj0RgVzsWMp5TLS7hJOk2L4uE2z7KUwq1M6DkuR5KrCE6FzDJq9z1H4ny9E2RdYzxWDmiSrKsAAJmi2LloSpLCO8AR2FRFsNicYdHUOjBPXnRcZTAABCEIwk6V8UrM+angy5rZlWtrcrs-LOpUsB1M0sqdMq6rflqudnpNdKmqWjavuhn7FMc7reoCqg9MGi7KRlMHWPI49xs8nyVFPc8sGmWagoEEKloAZjW2Y6c2mnkr1HaYD2+jSlO472U2M6TzPRwKbgK7bvux69VS8zXth-FYoZhHsTy5GuoB4rSu0iq9JG8HQyhlXGqs+mbO+jqUY1tHsMx-EhfJy8+j1-HmlMFZRGM5Q4mCMA3ZtTxxD4zRqk9aQSzoUplCORZlrp-owCB7XUV5fEFljzpfZnSpzsHSOsjJkXHZ3Pd4+t-rGhsNO6ZsQhsaXWwfQzTQbEzkOoNtAOgA)

**Entity/Service Definitions**
Include your entity model (or a model that sufficiently recreates your issue) to help troubleshoot.

```
{
  model: {
    service: 'test',
    entity: 'test',
    version: '1'
  },
  attributes: {
    id: {
      type: 'string',
      required: true,
      readOnly: true
    },
    organizationId: {
      type: 'string',
      required: true,
      readOnly: true,
    },
    accountId: {
      type: 'string',
    },
    createdAt: {
      type: 'string',
      readOnly: true,
      required: true,
      default: () => new Date().toJSON(),
      set: () => new Date().toJSON()
    },
    updatedAt: {
      type: 'string',
      watch: '*',
      required: true,
      default: () => new Date().toJSON(),
      set: () => new Date().toJSON()
    },
    settledAt: {
      type: 'string',
      default: 'n/a'
    },
    effectiveAt: {
      type: 'string',
      default: 'n/a'
    },
    type: {
      type: 'string',
      required: true
    },
    category: {
      type: 'string',
      required: true
    },
    amount: {
      type: 'string',
      required: true
    },
    description: {
      type: 'string'
    }
  },
  indexes: {
    entries: {
      pk: {
        field: 'pk',
        composite: ['organizationId']
      },
      sk: {
        field: 'sk',
        composite: ['id']
      }
    },
    entriesByAccount: {
      index: 'gsi1pk-gsi1sk-index',
      pk: {
        field: 'gsi1pk',
        composite: ['organizationId']
      },
      sk: {
        field: 'gsi1sk',
        composite: ['accountId', 'id']
      }
    },
    entriesBySettledDate: {
      index: 'gsi2pk-gsi2sk-index',
      condition: (attr) => attr.settledAt !== 'n/a',
      pk: {
        field: 'gsi2pk',
        composite: ['organizationId']
      },
      sk: {
        field: 'gsi2sk',
        composite: ['accountId', 'settledAt']
      }
    },
    entriesByEffectiveDate: {
      index: 'gsi3pk-gsi3sk-index',
      condition: (attr) => attr.effectiveAt !== 'n/a',
      pk: {
        field: 'gsi3pk',
        composite: ['organizationId']
      },
      sk: {
        field: 'gsi3sk',
        composite: ['accountId', 'effectiveAt']
      }
    }
  }
}
```

**Expected behavior**
I am unsure what the correct way of using `condition` here is.

**Comment by sam3d** [comment] 2024-04-10 09:02
I've also noticed I'm having the same issue, I feel like this isn't the expected behaviour. The `condition` implies that it applies to the whole index, and the `composite` helper could be used to fill in the missing gaps for the other attribute

**Comment by tywalch** [comment] 2024-04-10 15:52
Hi @nonken 👋 

You and @sam3d are correct, this isn't the best behavior in this case. As mentioned in @sam3d's post you can use the `composite` method as a stop gap [[example](https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAY1IBfbhiiSwAIkRwjVSzABGNgNzijUPrgVUGFwRSAF5bTShUDAB9AKC4aL4GSTgPLx8-MH4nTTAwvjgWVXUtAApRMCUKsElYRAAuKsrK4gxDE0aAcio8Kk78asrsrS6ev37BsH1MXCwfLoBGTurTAcqGKicsF1QxxsVJrBh9ycqqTWk4Lr9sPgBzCebm8jQscmOwJ3Q1p7I4BhgAHk+AhNI0vnBJqtJnI7gw+FgAF4bOZ8ACSHwOv0+FyuYE6Nyw90evxeqDecA+EJ+T3IAOBoPBGHQUJpYAYRm8qHUGJO2POl2uW2JrMmRjpPRgAEEqHzfgK8QThQ82ZU6UCQWDPsy4Kq-q93kzvqcwPAuAxKLKwKUAJR5AB8YAKRQAIhs4LaAHRUKAAKR0gIAcra9cQrbaHU7CmA3T0vT7-UHbaKnqhpDB3dKrVj5bihbcVSaWBsjHQuiASbS4AbKUbdSazRbqI0IyFHc6Y+7436A8GbaG4OG7W2o66uzbvT2kzaU80w1Rglm5U8FfmiYXsY3LV0+MAGMsntCnnAuFwHBppjLl81V-jCcS9Vvm-jd-vZ2c801c4K78rK89q3JQ1tRZQ82SMd07jkLUcxXT8lQLf81UAikqR1d92VqblsxNW8EPXJD9SA2sQMhMDJngXBxSwaQNHmL84J-fCRUPFYfiJeAAA88GvbJeFwa9KmkABrQTmi4HAEA+ToRMIypvBkKBZh6RoAG1OlheEkRRHwMU6ABdE0j1+XBRIY34JMQaTTLksAFNkZS8XUo4DKMjC+JwXAACFNClTlInUMSOLgTiujuWYFhEgBacKsAWUyouCzjCJEsTKksqSwoi2S9XkqwHPYJyNIwOEEWROj0RgVzsWMp5TLS7hJOk2L4uE2z7KUwq1M6DkuR5KrCE6FzDJq9z1H4ny9E2RdYzxWDmiSrKsAAJmi2LloSpLCO8AR2FRFsNicYdHUOjBPXnRcZTAABCEIwk6V8UrM+angy5rZlWtrcrs-LOpUsB1M0sqdMq6rflqudnpNdKmqWjavuhn7FMc7reoCqg9MGi7KRlMHWPI49xs8nyVFPc8sGmWagoEEKloAZjW2Y6c2mnkr1HaYD2+jSlO472U2M6TzPRwKbgK7bvux69VS8zXth-FYoZhHsTy5GuoB4rSu0iq9JG8HQyhlXGqs+mbO+jqUY1tHsMx-EhfJy8+j1-HmlMFZRGM5Q4mCMA3ZtTxRAVMA0R6SQMWGSyMCEMIcyORp7zuTxKiB7XUV5IhlU8N3RC4bkRZ8J0oAAcR0NEldKZQjkIFPyrTmBfcaEO4DD+ASkj3A7RzYBgD+XBLSEIlC7AAADRWROH60GCECJUBqYYfEpMBB5njAwDuTgsFwPu4BnZCqCiPgsnGzRJk9aQSzoCul5gauSq02vdPr0xd+ac7Byv+2RcdxpZs9PgoBYN2HQyoQzsn8jbD4NgFjLTpjYQg2Mly2B9BmTQNhfYv0qJ6KCtos7iBznnCqYBGC4BLmXESV8q5gBriDDEDdg6h3Dm3HAUdO7VG7r3fuS9D6jyZuPao5B94YEPnxE+Twz4XwoTfKhd9gY6yfhgsAb8qAfzJl-MWVpf7-0AROH0wCCygOtv1RoUCYFwKIIOBcOMrQ2GQQwVB6DT4W0KpI2+WsH6VQcWI7B-sPbpF8AoKAtFUTRy-HHfEgQjAkmoXIroZpljZ3-qQ8ugSKod08MQpJ5CUnBJ8aIIAA)], but this is something that should be addressed. I will review this area of code and see what can be done to change this 👍

**Comment by sam3d** [comment] 2024-04-12 16:38
@tywalch I think you're completely right. Similar to how a composite key is re-computed if any of its attributes change, the `condition` property behaves in a similar way.

What's interesting is that it's more akin to the `watch` property on attributes, where it _technically_ only wants to re-compute if dependent attributes are modified. The composite keys can do this because their dependent attributes are known, but `condition` doesn't have the same benefit. If there's an index `condition` it would need to be checked on every operation against that entity.

There's an issue with this – without knowing dependent attributes or the prior state of the entity's condition, during an update operation we don't know when the `condition` state transitions between `false` and `true`.

- `true` -> `false` – This is actually OK (and what you're describing above). There is a _bit_ of overhead in that we'll always be dropping the index's attributes, even if they were already not set.  But that's probably more something for the documentation than it is an actual issue with the implementation.
- `false` -> `true` – This one is harder. We don't know the previous state of the index, so we have to also set this index's attributes every time `condition` evaluates to `true`, even if we didn't touch any of those attributes.

Not 100% sure on a good solution here. A few ideas off the top of my head:

-  Add a list of dependent attributes to `condition` (like with `watch` on attributes) so we know when to re-compute the viability of the index. This would retain the current flexibility and fix index behaviour on mutations, with added complexity for the entity index definition
- Only allow `condition` to process the attributes defined on the `index` so if we're re-computing the index we know to also check for its condition. The downside is that this is scoped to the whole index, and not to the individual keys, so we couldn't update solely GSI1PK without also having to update GSI1SK if `condition` evaluates to `true`
- Allow `condition` to return more than just a boolean? No clue on what the API for this would look like, but perhaps `condition` could look at the attributes its passed in the mutation and make the decision to either `false` (delete the index), `true` (create the index), or `null` (don't try to drop or create the index):

```ts
condition: (attr) => {
  // effectiveAt not changed, don't create OR drop the index
  if (attr.effectiveAt === undefined) return null;

  // Drop the index if needed
  if (attr.effectiveAt === "n/a") return false;

  // Otherwise re-create the index
  return true;
},
```

Either way, if we then undergo a state transition because a dependent attribute changed, then the usual `.composite()` helper can take over to fill out the index as needed (and error if not provided). And we know we did _need_ to do that because the dependent attributes changed.

**Comment by sam3d** [comment] 2024-04-12 19:17
Actually wait I've been thinking about this some more, this might be more complex than I thought.

Going from `true`/`false` -> `false` is always okay, because if `condition` is `false` then the indexes can always just be dropped and aren't dependent on the previous state of those attributes.

In the case of the condition going from `false` -> `true`, then your example makes sense. However, I feel like without some way to model that state transition, then we can't differentiate between `false` -> `true` and `true` -> `true`. Which is really annoying. We only want to set those index attributes when the condition flips (or if the attributes change), but without some way to model that then all of the index attributes must be set every single time.

Is it maybe possible to do some kind of check where if the `condition` evaluates to `true` then it applies an extra condition expression to ensure that the entity has the attributes for that index? And then it'll fail and force the use of the `composite` helper in order to perform the update?

**Comment by tywalch** [comment] 2024-04-12 21:59
I mulled it around a bit today, but I think I got it; let me know what you think:

1. The `condition` callback will be invoked _only_ when a composite attribute associated with an index is `set` via an `update`, `patch`, or `upsert`. [existing behavior]
2. The `condition` callback is provided the attributes being `set` on that particular operation, including the item's identifying composite attributes. [existing behavior]
3. If the `condition` callback returns `true`, ElectroDB will attempt to create the index and all of its associated keys. If an index cannot be created because an `update` operation only has enough context for a partial key, ElectroDB will throw. [the original issue here, fixed]
4. If the `condition` callback returns `false`, the index and all of its associated keys will be removed from the item. [new behavior]

 Item #1 above is the key to solving the issue you bring up in your first comment, and it's actually what we do currently. This means that `condition` would only be called when an index must be recalculated. furthermore, as described in #3, ElectroDB will actually throw if your `update` operation (`set` and `remove`) lacks a full composite context and would result in a "partial" key. This would mean that all `* -> true` transitions are already validated to have all the composite parts necessary to recreate the complete index already.
 
Let me know if this doesn't make sense or I am missing anything. I am writing some tests now, but likely won't be making a PR until tomorrow. I'm definitely not looking to rush a change like this.

**Comment by sam3d** [comment] 2024-04-13 07:50
I think this makes sense! With the two caveats worth documenting:

1. A `condition` cannot be solely dependent on attributes outside of that composite index. This means that patterns like the following wouldn't work:

```ts
{
  condition: (attr) => !attr.deletedAt,
  pk: { field: "GSI1PK", composite: [] },
  sk: { field: "GSI1SK", composite: ["createdAt"] },
}
```

2. An index with a `condition` cannot be updated unless _all_ composite attributes are provided, not just the ones from the field. For example, currently this is the unsound behaviour:

```ts
{
  pk: { field: "GSI1PK", composite: ["storeId"] },
  sk: { field: "GSI1SK", composite: ["status", "createdAt"] },
}

// Updates GSI1PK, no problem
entity.patch({ id: "29381" }).set({ storeId: "SJR" }).go();
```

But in order to perform the same operation with a `condition`:

```ts
{
  condition: (attr) => attr.status !== "deleted",
  pk: { field: "GSI1PK", composite: ["storeId"] },
  sk: { field: "GSI1SK", composite: ["status", "createdAt"] },
};

// Condition returns true, so we need to set GSI1PK and GSI1SK in case the index
// doesn't already exist. We now MUST provide status and createdAt
entity.patch({ id: "29381" }).set({ storeId: "SJR" }).go();

// So this must be done instead every time
entity
  .patch({ id: "29381" })
  .set({ storeId: "SJR" })
  .composite({ status: prevEntity.status, createdAt: prevEntity.createdAt })
  .go();
```

**Comment by sam3d** [comment] 2024-04-13 07:53
DynamoDB doesn't propagate to a composite index unless both attributes are present, right? So to remove an entity from a sparse index you technically don't have to drop both, just one of them. Maybe the result of `condition` only gets applied to the composite key _field_ that's being mutated?

**Comment by tywalch** [comment] 2024-04-14 20:09
> A condition cannot be solely dependent on attributes outside of that composite index. This means that patterns like the following wouldn't work.

My gut is that the _user_ would determine if they wish to check attributes outside the composite; i.e. that Electro would continue to supply the `condition` callback with all values being "set". I do agree it is necessary to reiterate in the docs that the attributes being passed represent the values provided in the operation and not the item as it is stored.

> An index with a condition cannot be updated unless all composite attributes are provided, not just the ones from the field. For example:
> // Condition returns true, so we need to set GSI1PK and GSI1SK in case the index
> // doesn't already exist. We now MUST provide status and createdAt

This is a very, very good point. You're saying that because this could be the first time the `condition` callback has returned `true`, but the user only provided enough data on update to create one out of the two keys. In that case, it is also possible that the stored item actually has all the values necessary to form the other key. In this case the user has an expectation that the index will be written, but in reality, they now have an orphaned index record that is not consistent with the underlying attributes. 

Great catch! This is sort of the opposite of the issue I brought up above, I had not considered this 🤯 

> DynamoDB doesn't propagate to a composite index unless both attributes are present, right? So to remove an entity from a sparse index you technically don't have to drop both, just one of them. Maybe the result of condition only gets applied to the composite key field that's being mutated?

How might this work?

> 2. An index with a condition cannot be updated unless all composite attributes are provided, not just the ones from the field. For example:

Do you think this problem becomes "solved" by adding this requirement? It sort of seems like it? That said, this will be difficult for newbies to understand, not to mention this would become a request time validation which makes it doubly hard for users to anticipate. 

--------------------------

While it does feel like we're close to solving this, I don't want to be too precious about the current API for handling this. I haven't squared the circle in my mind, but this topic does _feel_ like it could have a meaningful overlap with [Ross Gerbasi's request](https://discord.com/channels/983865673656705025/994984119224246303/1214065958549717053) for the ability to `build` and `drop` specific indexes. His need revolves around backfilling new created indexes on existing items. 

I sat down recently and thought about what that API would look like. Creating an API for dropping an index was very straight forward, but I found an API for building a specific index had a lot complexities due to potential attribute dependencies. The simplest approach would be to simply accept composite values "as-is" (i.e. without any setter processing) and add an automatic `eq` condition on each attribute provided. Additionally, this functionality wouldn't play nice with `condition`; it would likely have to skip the check to work as anticipated.

Thinking through that feature had me thinking there must be some kind of third way. Does this spark anything in you?

**Comment by aphex** [comment] 2024-04-17 18:54
Hey @tywalch so I must admit I haven't spent much time thinking about a broader API and requirements of the library. I have no doubt this is much more complex. We would be good with a very specific `Entity` `reindex` method. Expectations would be I provide all attributes to write all indexes or provide some parameters to just target a few or one index. 

The use case we are looking to handle is one where attributes already exist in an `Entity`, so all the data is there, we just need to have better access to it. So we will be scanning the entity and running this process against all items. Maybe electro can even provide help here with a utility to reindex all of an Entity quickly. A combination of concurrent PUTs and queuing for tables with millions of items. The other tool we've used for this is Dynobase but its import is slow compared to a custom script.

Not sure how much this connects with the `condition` conversation here. However there are likely all sorts of other use cases for index scenarios. Another obvious one would be attributes that do not exist are being added and indexed. 

We would also need to keep our `createdAt` and `updatedAt` dates. Here's an example of how we configure these in our entities is below. Not sure what the best way forward to keep these values unchanged while we add/remove indexes

```ts
createdAt: {
      type: 'string',
      readOnly: true,
      required: true,
      default: getNowISO,
      set: getNowISO,
    },
    updatedAt: {
      type: 'string',
      watch: '*',
      required: true,
      default: getNowISO,
      set: getNowISO,
    },
```

**Comment by goosefraba** [comment] 2024-04-18 16:46
I ran into this issue today as well as I'm new to ElectroDB but using sparse index pretty heavy.

My use-case is similar to what have been said by others already.

`state: 'ACTIVE' | 'INACTIVE'`

and I just want to have ACTIVE ones in the GSI1 index and get removed once I update the state.

Any idea if there will a fix soon? Or is there any workaround?

**Comment by tywalch** [comment] 2024-04-27 21:31
Small update: this is still a WIP, I made significant progress this afternoon, still ironing out tests for edge cases 👍

**Comment by nonken** [comment] 2024-05-01 18:01
@tywalch this is so good, thank you a million times for diving into this. Can we somehow donate, as in, does the sponsoring work for you?

**Comment by tywalch** [comment] 2024-05-01 18:56
> @tywalch this is so good, thank you a million times for diving into this. Can we somehow donate, as in, does the sponsoring work for you?

No problem, glad it worked and I'm happy you raised this because it helps everyone!

Yup, I'm setup for sponsoring via GitHub's native sponsoring option (if that works) -- thank you so much for considering me for sponsorship!

**Comment by tywalch** [comment] 2024-05-03 15:44
Closing, but feel free to reopen!

**Closed by tywalch** 2024-05-03 15:44 UTC

**Comment by severi** [comment] 2024-05-17 09:17
This update unfortunately started causing issues for us. One example use case would be something like this
- store chat messages for a given chat session
- chat sessions can be either "unauthenticated" or "attached to logged in users"

previously we had a sparse index for accessing chats by user id (see example entity definition here), and it worked well with v2.13.1.  For instance, if a user logs in while having an active chatsession, the unauthenticated chat session is correctly added to the "byUser"-index when the "loggedInUserId" attribute is set (for unauthenticated users it is undefined).

It seems this is no longer supported, or is there some way to still achieve this? The upsert operation we used to create/update the message entries started failing, which was unexpected for a minor version upgrade.

I believe this is a valid use case for sparse indices, and it's unfortunate if the library no longer supports it.

```
{
  model: {
    entity: 'chatConversation',
    version: '1.0',
    service: 'chatbot',
  },
  attributes: {
    conversationId: {
      type: 'string',
      required: true,
    },
    loggedInUserId: {
      type: 'string',
      required: false,
    },
    messages: {
      type: 'list',
      items: {
        type: 'any',
      },
      required: true,
    },
  },
  indexes: {
    byConversationId: {
      pk: {
        field: 'pk',
        composite: ['conversationId'],
        casing: 'none',
      },
      sk: {
        field: 'sk',
        composite: [],
        casing: 'none',
      },
    },
    byUser: {
      collection: 'userData',
      index: 'gsi1pk-gsi1sk-index',
      type: 'clustered',
      condition: (attr: any) => {
        return !!attr.loggedInUserId;
      },
      pk: {
        field: 'gsi1pk',
        composite: ['loggedInUserId'],
        casing: 'none',
      },
      sk: {
        field: 'gsi1sk',
        composite: ['conversationId'],
        casing: 'none',
      },
    },
  },
};
```

**Comment by tywalch** [comment] 2024-05-17 16:45
Hi @severi 

Firstly, I want to say that I am sorry your existing code broke do to this fix. I try very hard to make sure this does not happen. Ultimately in choosing between a `major` and `minor` update, I chose a `minor` update because the original implementation had such a significant implementation flaw it was not viable as it was.

As for how you might achieve what you had, I have two potential approaches for you:

1. Use `get` and `set` to apply an empty string when no `loggedInUserId` is provided ([example](https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAY1IBfbhiiSwAIkRwjVSzABGNgNzijUPrgVUGFwRSAF5bTShUDAB9AKC4aL4GSTgPLx8-MCNGKgBhH31MXAYNHzAwvjgWVXUtAApFUTAwSVhEAC4lJuawfg0qTU6AcmyS-L5CjGLSviH8bubJ3CwfYYBGADoABjmFogNjOGHRqhcoKl3m03nmkqcsF1QqPE7GnqyCopKVvgBJGFee2aA2kRzAQz82D4AHNLu8yHA0FhyACwE50Dcetc9ggoNDoXAYL8+ABVYgYf6A+FozSg4aQrAwuHvchIlGdLgMBDETHvYhUTp1fRcgCU5QAfF1qc0sFwwEKueUQmFUAI4FxGYSxW9pc1yFQonxwUNPLrTECevrDWBhQhTfDsdSCQL5baxSFJTrqbLXYrlWEhkNtRaWXADRgjar4BrKjB7dTzbqrRGbVz41i9o6eilcMUCbgqfCQWChggsH5mT12HBJAWpdLi8MGHxNJWrrzLYjUMjCZ10XAO1ms4z4AAPF715ouTTjJbfHyUyc9aQAa0L1I1iFRQ1XbZ63hkUGWz06AG0Rp8pvO-jAhgBdDvvIwMZYw4Z8HxwPdZvlrpfvTcEG3XAVz3ZoD1kY8wVPB8QyyF9GWhd9P2-QcO2nMlMHXKs1VHYZoWWNZVwAWgIrA1hA4iRzgUc90bcEjAQVA-EwQk928AR2B+QU7gwTpm00d1PTg5MjQAQjE3iNlxfFCWJTCKTjC0f2XP8vXhQDtzIojQMffcrEg6sz1LPECSJUlyX+e89PAhC33BD9KlQi0QOwgCcCA-DCJAsCPkPKDjI4ucZis2DdWfV8kIclC9JUod5muJQ0UCYIwHNEVPFEYBgFYLAECQD8FFxGFMDROhLBYUQTlnL4Zg2IxyBKOAGm6ILap+RchjWAAmABmOEczzCcYMxGSzPkyzUSjdVNRgBKRQ2aEoDqDKgA)). This approach ideally won't require your app code to change.

2. You could simply pass an empty string for `loggedInUserId` instead of omitting the value. This might require some change in your app code to account for an empty string vs `undefined`

Again, please accept my apology for the unexpected errors in your app, and let me know if any of the above will work for you; If the above won't work in your case, I can work to maybe create an escape hatch (via an execution option or some type of configuration) for this requirement.
